// Code generated by protoc-gen-go. DO NOT EDIT.
// source: addressmetadata.proto

package models

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Signature type provided.  Default is Schnorr, but can be ecdsa
type AddressMetadata_SignatureType int32

const (
	AddressMetadata_Schnorr AddressMetadata_SignatureType = 0
	AddressMetadata_ECDSA   AddressMetadata_SignatureType = 1
)

var AddressMetadata_SignatureType_name = map[int32]string{
	0: "Schnorr",
	1: "ECDSA",
}

var AddressMetadata_SignatureType_value = map[string]int32{
	"Schnorr": 0,
	"ECDSA":   1,
}

func (x AddressMetadata_SignatureType) String() string {
	return proto.EnumName(AddressMetadata_SignatureType_name, int32(x))
}

func (AddressMetadata_SignatureType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_0e2f0794313d73e1, []int{3, 0}
}

type Header struct {
	Name                 string   `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Value                string   `protobuf:"bytes,2,opt,name=Value,proto3" json:"Value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Header) Reset()         { *m = Header{} }
func (m *Header) String() string { return proto.CompactTextString(m) }
func (*Header) ProtoMessage()    {}
func (*Header) Descriptor() ([]byte, []int) {
	return fileDescriptor_0e2f0794313d73e1, []int{0}
}

func (m *Header) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Header.Unmarshal(m, b)
}
func (m *Header) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Header.Marshal(b, m, deterministic)
}
func (m *Header) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Header.Merge(m, src)
}
func (m *Header) XXX_Size() int {
	return xxx_messageInfo_Header.Size(m)
}
func (m *Header) XXX_DiscardUnknown() {
	xxx_messageInfo_Header.DiscardUnknown(m)
}

var xxx_messageInfo_Header proto.InternalMessageInfo

func (m *Header) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Header) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

// Row is an indidual piece of structured data provided by wallet authors.
// The headers help wallets determine how to deserialize the data for their purposes.
type MetadataField struct {
	Headers              []*Header `protobuf:"bytes,1,rep,name=Headers,proto3" json:"Headers,omitempty"`
	Metadata             []byte    `protobuf:"bytes,2,opt,name=Metadata,proto3" json:"Metadata,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *MetadataField) Reset()         { *m = MetadataField{} }
func (m *MetadataField) String() string { return proto.CompactTextString(m) }
func (*MetadataField) ProtoMessage()    {}
func (*MetadataField) Descriptor() ([]byte, []int) {
	return fileDescriptor_0e2f0794313d73e1, []int{1}
}

func (m *MetadataField) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MetadataField.Unmarshal(m, b)
}
func (m *MetadataField) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MetadataField.Marshal(b, m, deterministic)
}
func (m *MetadataField) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MetadataField.Merge(m, src)
}
func (m *MetadataField) XXX_Size() int {
	return xxx_messageInfo_MetadataField.Size(m)
}
func (m *MetadataField) XXX_DiscardUnknown() {
	xxx_messageInfo_MetadataField.DiscardUnknown(m)
}

var xxx_messageInfo_MetadataField proto.InternalMessageInfo

func (m *MetadataField) GetHeaders() []*Header {
	if m != nil {
		return m.Headers
	}
	return nil
}

func (m *MetadataField) GetMetadata() []byte {
	if m != nil {
		return m.Metadata
	}
	return nil
}

// Message is the user-specified data section of a AddressMetadata that is covered by the Signature provided by the user
type Payload struct {
	// Timestamp allows servers to determine which version of the data is the most recent.
	Timestamp int64 `protobuf:"varint,1,opt,name=Timestamp,proto3" json:"Timestamp,omitempty"`
	// TTL tells us how long this entry should exist before being considered invalid.
	TTL int64 `protobuf:"varint,2,opt,name=TTL,proto3" json:"TTL,omitempty"`
	// User specified data.  Presumably some conventional data determined by wallet authors
	Rows                 []*MetadataField `protobuf:"bytes,3,rep,name=Rows,proto3" json:"Rows,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *Payload) Reset()         { *m = Payload{} }
func (m *Payload) String() string { return proto.CompactTextString(m) }
func (*Payload) ProtoMessage()    {}
func (*Payload) Descriptor() ([]byte, []int) {
	return fileDescriptor_0e2f0794313d73e1, []int{2}
}

func (m *Payload) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Payload.Unmarshal(m, b)
}
func (m *Payload) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Payload.Marshal(b, m, deterministic)
}
func (m *Payload) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Payload.Merge(m, src)
}
func (m *Payload) XXX_Size() int {
	return xxx_messageInfo_Payload.Size(m)
}
func (m *Payload) XXX_DiscardUnknown() {
	xxx_messageInfo_Payload.DiscardUnknown(m)
}

var xxx_messageInfo_Payload proto.InternalMessageInfo

func (m *Payload) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *Payload) GetTTL() int64 {
	if m != nil {
		return m.TTL
	}
	return 0
}

func (m *Payload) GetRows() []*MetadataField {
	if m != nil {
		return m.Rows
	}
	return nil
}

// AddressMetadata is the basic unit of the keytp server.  It is used in both PUT and GET requests for various keyids
type AddressMetadata struct {
	// Serialized version of the XPubKey.  The *hash* of this XPub should correspond to the `key` in the kv store
	PubKey []byte `protobuf:"bytes,1,opt,name=PubKey,proto3" json:"PubKey,omitempty"`
	// Signature is the signature of the metadata by XPubKey
	Signature []byte                        `protobuf:"bytes,2,opt,name=Signature,proto3" json:"Signature,omitempty"`
	Type      AddressMetadata_SignatureType `protobuf:"varint,3,opt,name=Type,proto3,enum=models.AddressMetadata_SignatureType" json:"Type,omitempty"`
	// Payload is the metadata set by the user, and covered by the signature.
	Payload              *Payload `protobuf:"bytes,4,opt,name=Payload,proto3" json:"Payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddressMetadata) Reset()         { *m = AddressMetadata{} }
func (m *AddressMetadata) String() string { return proto.CompactTextString(m) }
func (*AddressMetadata) ProtoMessage()    {}
func (*AddressMetadata) Descriptor() ([]byte, []int) {
	return fileDescriptor_0e2f0794313d73e1, []int{3}
}

func (m *AddressMetadata) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddressMetadata.Unmarshal(m, b)
}
func (m *AddressMetadata) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddressMetadata.Marshal(b, m, deterministic)
}
func (m *AddressMetadata) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddressMetadata.Merge(m, src)
}
func (m *AddressMetadata) XXX_Size() int {
	return xxx_messageInfo_AddressMetadata.Size(m)
}
func (m *AddressMetadata) XXX_DiscardUnknown() {
	xxx_messageInfo_AddressMetadata.DiscardUnknown(m)
}

var xxx_messageInfo_AddressMetadata proto.InternalMessageInfo

func (m *AddressMetadata) GetPubKey() []byte {
	if m != nil {
		return m.PubKey
	}
	return nil
}

func (m *AddressMetadata) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

func (m *AddressMetadata) GetType() AddressMetadata_SignatureType {
	if m != nil {
		return m.Type
	}
	return AddressMetadata_Schnorr
}

func (m *AddressMetadata) GetPayload() *Payload {
	if m != nil {
		return m.Payload
	}
	return nil
}

func init() {
	proto.RegisterEnum("models.AddressMetadata_SignatureType", AddressMetadata_SignatureType_name, AddressMetadata_SignatureType_value)
	proto.RegisterType((*Header)(nil), "models.Header")
	proto.RegisterType((*MetadataField)(nil), "models.MetadataField")
	proto.RegisterType((*Payload)(nil), "models.Payload")
	proto.RegisterType((*AddressMetadata)(nil), "models.AddressMetadata")
}

func init() { proto.RegisterFile("addressmetadata.proto", fileDescriptor_0e2f0794313d73e1) }

var fileDescriptor_0e2f0794313d73e1 = []byte{
	// 314 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x51, 0x4b, 0x4b, 0xf3, 0x40,
	0x14, 0xfd, 0xe6, 0x4b, 0x9a, 0xda, 0xdb, 0x27, 0x17, 0x2b, 0x41, 0x5c, 0x84, 0x80, 0x98, 0x6e,
	0xb2, 0x88, 0x2b, 0x97, 0xc5, 0x07, 0x82, 0x0f, 0xca, 0x34, 0xba, 0x9f, 0x3a, 0x17, 0x2d, 0x24,
	0x9d, 0x32, 0x93, 0x22, 0xfd, 0xa3, 0xfe, 0x1e, 0xe9, 0x24, 0xd3, 0x52, 0x77, 0xf7, 0x9e, 0x73,
	0xcf, 0x23, 0x19, 0x18, 0x0b, 0x29, 0x35, 0x19, 0x53, 0x52, 0x25, 0xa4, 0xa8, 0x44, 0xba, 0xd6,
	0xaa, 0x52, 0x18, 0x94, 0x4a, 0x52, 0x61, 0xe2, 0x0c, 0x82, 0x47, 0x12, 0x92, 0x34, 0x22, 0xf8,
	0xaf, 0xa2, 0xa4, 0x90, 0x45, 0x2c, 0xe9, 0x70, 0x3b, 0xe3, 0x29, 0xb4, 0xde, 0x45, 0xb1, 0xa1,
	0xf0, 0xbf, 0x05, 0xeb, 0x25, 0x7e, 0x83, 0xfe, 0x4b, 0xe3, 0xf6, 0xb0, 0xa4, 0x42, 0x62, 0x02,
	0xed, 0xda, 0xc4, 0x84, 0x2c, 0xf2, 0x92, 0x6e, 0x36, 0x48, 0x6b, 0xfb, 0xb4, 0x86, 0xb9, 0xa3,
	0xf1, 0x1c, 0x4e, 0x9c, 0xd4, 0x7a, 0xf6, 0xf8, 0x7e, 0x8f, 0x25, 0xb4, 0x67, 0x62, 0x5b, 0x28,
	0x21, 0xf1, 0x02, 0x3a, 0xf9, 0xb2, 0x24, 0x53, 0x89, 0x72, 0x6d, 0x0b, 0x79, 0xfc, 0x00, 0xe0,
	0x08, 0xbc, 0x3c, 0x7f, 0xb6, 0x7a, 0x8f, 0xef, 0x46, 0x9c, 0x80, 0xcf, 0xd5, 0xb7, 0x09, 0x3d,
	0x9b, 0x3e, 0x76, 0xe9, 0x47, 0x2d, 0xb9, 0x3d, 0x89, 0x7f, 0x18, 0x0c, 0xa7, 0xf5, 0x2f, 0x71,
	0x34, 0x9e, 0x41, 0x30, 0xdb, 0x2c, 0x9e, 0x68, 0x6b, 0xb3, 0x7a, 0xbc, 0xd9, 0x76, 0x35, 0xe6,
	0xcb, 0xcf, 0x95, 0xa8, 0x36, 0x9a, 0x9a, 0xba, 0x07, 0x00, 0x6f, 0xc0, 0xcf, 0xb7, 0x6b, 0x0a,
	0xbd, 0x88, 0x25, 0x83, 0xec, 0xd2, 0x85, 0xfe, 0x31, 0x4f, 0xf7, 0x82, 0xdd, 0x31, 0xb7, 0x12,
	0x9c, 0xec, 0x3f, 0x35, 0xf4, 0x23, 0x96, 0x74, 0xb3, 0xa1, 0x53, 0x37, 0x30, 0x77, 0x7c, 0x7c,
	0x05, 0xfd, 0x23, 0x07, 0xec, 0x42, 0x7b, 0xfe, 0xf1, 0xb5, 0x52, 0x5a, 0x8f, 0xfe, 0x61, 0x07,
	0x5a, 0xf7, 0xb7, 0x77, 0xf3, 0xe9, 0x88, 0x2d, 0x02, 0xfb, 0xb0, 0xd7, 0xbf, 0x01, 0x00, 0x00,
	0xff, 0xff, 0x6f, 0x85, 0x0e, 0x4f, 0xf1, 0x01, 0x00, 0x00,
}
