// Code generated by protoc-gen-go. DO NOT EDIT.
// source: addressmetadata.proto

package models

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Signature scheme provided.  Default is Schnorr, but can be ecdsa.
type AddressMetadata_SignatureScheme int32

const (
	AddressMetadata_SCHNORR AddressMetadata_SignatureScheme = 0
	AddressMetadata_ECDSA   AddressMetadata_SignatureScheme = 1
)

var AddressMetadata_SignatureScheme_name = map[int32]string{
	0: "SCHNORR",
	1: "ECDSA",
}

var AddressMetadata_SignatureScheme_value = map[string]int32{
	"SCHNORR": 0,
	"ECDSA":   1,
}

func (x AddressMetadata_SignatureScheme) String() string {
	return proto.EnumName(AddressMetadata_SignatureScheme_name, int32(x))
}

func (AddressMetadata_SignatureScheme) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_0e2f0794313d73e1, []int{3, 0}
}

// Basic key/value used to store header data.
type Header struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value                string   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Header) Reset()         { *m = Header{} }
func (m *Header) String() string { return proto.CompactTextString(m) }
func (*Header) ProtoMessage()    {}
func (*Header) Descriptor() ([]byte, []int) {
	return fileDescriptor_0e2f0794313d73e1, []int{0}
}

func (m *Header) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Header.Unmarshal(m, b)
}
func (m *Header) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Header.Marshal(b, m, deterministic)
}
func (m *Header) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Header.Merge(m, src)
}
func (m *Header) XXX_Size() int {
	return xxx_messageInfo_Header.Size(m)
}
func (m *Header) XXX_DiscardUnknown() {
	xxx_messageInfo_Header.DiscardUnknown(m)
}

var xxx_messageInfo_Header proto.InternalMessageInfo

func (m *Header) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Header) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

// MetadataField is an indidual piece of structured data provided by wallet authors.
type MetadataField struct {
	// The headers help wallets determine how to deserialize the data.
	Headers []*Header `protobuf:"bytes,1,rep,name=headers,proto3" json:"headers,omitempty"`
	// Body of the metadata field.
	Metadata             []byte   `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MetadataField) Reset()         { *m = MetadataField{} }
func (m *MetadataField) String() string { return proto.CompactTextString(m) }
func (*MetadataField) ProtoMessage()    {}
func (*MetadataField) Descriptor() ([]byte, []int) {
	return fileDescriptor_0e2f0794313d73e1, []int{1}
}

func (m *MetadataField) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MetadataField.Unmarshal(m, b)
}
func (m *MetadataField) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MetadataField.Marshal(b, m, deterministic)
}
func (m *MetadataField) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MetadataField.Merge(m, src)
}
func (m *MetadataField) XXX_Size() int {
	return xxx_messageInfo_MetadataField.Size(m)
}
func (m *MetadataField) XXX_DiscardUnknown() {
	xxx_messageInfo_MetadataField.DiscardUnknown(m)
}

var xxx_messageInfo_MetadataField proto.InternalMessageInfo

func (m *MetadataField) GetHeaders() []*Header {
	if m != nil {
		return m.Headers
	}
	return nil
}

func (m *MetadataField) GetMetadata() []byte {
	if m != nil {
		return m.Metadata
	}
	return nil
}

// Payload is the user-specified data section of a AddressMetadata that is covered by the users signature.
type Payload struct {
	// Timestamp allows servers to determine which version of the data is the most recent.
	Timestamp int64 `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// TTL tells us how long this entry should exist before being considered invalid.
	Ttl int64 `protobuf:"varint,2,opt,name=ttl,proto3" json:"ttl,omitempty"`
	// User specified data.  Presumably some conventional data determined by wallet authors.
	Rows                 []*MetadataField `protobuf:"bytes,3,rep,name=rows,proto3" json:"rows,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *Payload) Reset()         { *m = Payload{} }
func (m *Payload) String() string { return proto.CompactTextString(m) }
func (*Payload) ProtoMessage()    {}
func (*Payload) Descriptor() ([]byte, []int) {
	return fileDescriptor_0e2f0794313d73e1, []int{2}
}

func (m *Payload) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Payload.Unmarshal(m, b)
}
func (m *Payload) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Payload.Marshal(b, m, deterministic)
}
func (m *Payload) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Payload.Merge(m, src)
}
func (m *Payload) XXX_Size() int {
	return xxx_messageInfo_Payload.Size(m)
}
func (m *Payload) XXX_DiscardUnknown() {
	xxx_messageInfo_Payload.DiscardUnknown(m)
}

var xxx_messageInfo_Payload proto.InternalMessageInfo

func (m *Payload) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *Payload) GetTtl() int64 {
	if m != nil {
		return m.Ttl
	}
	return 0
}

func (m *Payload) GetRows() []*MetadataField {
	if m != nil {
		return m.Rows
	}
	return nil
}

// AddressMetadata is the basic unit of the keyserver.  It is used in both PUT and GET requests.
type AddressMetadata struct {
	// Serialized version of the XPubKey.  The *hash* of this XPub should correspond to the `key` in the kv store.
	PubKey []byte `protobuf:"bytes,1,opt,name=pub_key,json=pubKey,proto3" json:"pub_key,omitempty"`
	// Signature is the signature of the metadata by XPubKey.
	Signature []byte                          `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	Scheme    AddressMetadata_SignatureScheme `protobuf:"varint,3,opt,name=scheme,proto3,enum=models.AddressMetadata_SignatureScheme" json:"scheme,omitempty"`
	// Payload is the metadata set by the user, and covered by the signature.
	Payload              *Payload `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddressMetadata) Reset()         { *m = AddressMetadata{} }
func (m *AddressMetadata) String() string { return proto.CompactTextString(m) }
func (*AddressMetadata) ProtoMessage()    {}
func (*AddressMetadata) Descriptor() ([]byte, []int) {
	return fileDescriptor_0e2f0794313d73e1, []int{3}
}

func (m *AddressMetadata) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddressMetadata.Unmarshal(m, b)
}
func (m *AddressMetadata) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddressMetadata.Marshal(b, m, deterministic)
}
func (m *AddressMetadata) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddressMetadata.Merge(m, src)
}
func (m *AddressMetadata) XXX_Size() int {
	return xxx_messageInfo_AddressMetadata.Size(m)
}
func (m *AddressMetadata) XXX_DiscardUnknown() {
	xxx_messageInfo_AddressMetadata.DiscardUnknown(m)
}

var xxx_messageInfo_AddressMetadata proto.InternalMessageInfo

func (m *AddressMetadata) GetPubKey() []byte {
	if m != nil {
		return m.PubKey
	}
	return nil
}

func (m *AddressMetadata) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

func (m *AddressMetadata) GetScheme() AddressMetadata_SignatureScheme {
	if m != nil {
		return m.Scheme
	}
	return AddressMetadata_SCHNORR
}

func (m *AddressMetadata) GetPayload() *Payload {
	if m != nil {
		return m.Payload
	}
	return nil
}

func init() {
	proto.RegisterEnum("models.AddressMetadata_SignatureScheme", AddressMetadata_SignatureScheme_name, AddressMetadata_SignatureScheme_value)
	proto.RegisterType((*Header)(nil), "models.Header")
	proto.RegisterType((*MetadataField)(nil), "models.MetadataField")
	proto.RegisterType((*Payload)(nil), "models.Payload")
	proto.RegisterType((*AddressMetadata)(nil), "models.AddressMetadata")
}

func init() { proto.RegisterFile("addressmetadata.proto", fileDescriptor_0e2f0794313d73e1) }

var fileDescriptor_0e2f0794313d73e1 = []byte{
	// 323 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x91, 0xcd, 0x4e, 0xc2, 0x40,
	0x10, 0xc7, 0x5d, 0x0b, 0xad, 0x0c, 0x08, 0x64, 0x22, 0xb1, 0x31, 0x1e, 0x9a, 0x5e, 0x2c, 0x97,
	0x1e, 0xea, 0x03, 0x18, 0x82, 0x1a, 0x12, 0xe3, 0x47, 0xb6, 0xf1, 0x6c, 0x16, 0x77, 0x22, 0xc4,
	0x96, 0x36, 0xdd, 0xad, 0x86, 0xa7, 0xf5, 0x55, 0x0c, 0xdb, 0xae, 0x44, 0x6e, 0xf3, 0xf9, 0xfb,
	0xff, 0x77, 0x16, 0x26, 0x42, 0xca, 0x8a, 0x94, 0xca, 0x49, 0x0b, 0x29, 0xb4, 0x88, 0xcb, 0xaa,
	0xd0, 0x05, 0xba, 0x79, 0x21, 0x29, 0x53, 0x61, 0x02, 0xee, 0x82, 0x84, 0xa4, 0x0a, 0x11, 0x3a,
	0x1b, 0x91, 0x93, 0xcf, 0x02, 0x16, 0xf5, 0xb8, 0x89, 0xf1, 0x0c, 0xba, 0x5f, 0x22, 0xab, 0xc9,
	0x3f, 0x36, 0xc5, 0x26, 0x09, 0x5f, 0xe1, 0xf4, 0xb1, 0xa5, 0xdd, 0xaf, 0x29, 0x93, 0x18, 0x81,
	0xb7, 0x32, 0x10, 0xe5, 0xb3, 0xc0, 0x89, 0xfa, 0xc9, 0x30, 0x6e, 0xf0, 0x71, 0xc3, 0xe6, 0xb6,
	0x8d, 0x17, 0x70, 0x62, 0x8d, 0x18, 0xe6, 0x80, 0xff, 0xe5, 0xa1, 0x04, 0xef, 0x45, 0x6c, 0xb3,
	0x42, 0x48, 0xbc, 0x84, 0x9e, 0x5e, 0xe7, 0xa4, 0xb4, 0xc8, 0x4b, 0x63, 0xc8, 0xe1, 0xfb, 0x02,
	0x8e, 0xc1, 0xd1, 0x3a, 0x33, 0xfb, 0x0e, 0xdf, 0x85, 0x38, 0x85, 0x4e, 0x55, 0x7c, 0x2b, 0xdf,
	0x31, 0xea, 0x13, 0xab, 0xfe, 0xcf, 0x25, 0x37, 0x23, 0xe1, 0x0f, 0x83, 0xd1, 0xac, 0x39, 0x89,
	0x6d, 0xe3, 0x39, 0x78, 0x65, 0xbd, 0x7c, 0xfb, 0xa4, 0xad, 0x11, 0x1b, 0x70, 0xb7, 0xac, 0x97,
	0x0f, 0xb4, 0xdd, 0xf9, 0x50, 0xeb, 0x8f, 0x8d, 0xd0, 0x75, 0x45, 0xad, 0xdf, 0x7d, 0x01, 0x6f,
	0xc0, 0x55, 0xef, 0x2b, 0xca, 0xc9, 0x77, 0x02, 0x16, 0x0d, 0x93, 0x2b, 0xab, 0x7b, 0xc0, 0x8f,
	0x53, 0xbb, 0x92, 0x9a, 0x71, 0xde, 0xae, 0xe1, 0x14, 0xbc, 0xb2, 0x79, 0xb1, 0xdf, 0x09, 0x58,
	0xd4, 0x4f, 0x46, 0x96, 0xd0, 0x1e, 0x82, 0xdb, 0x7e, 0x38, 0x85, 0xd1, 0x01, 0x05, 0xfb, 0xe0,
	0xa5, 0xf3, 0xc5, 0xd3, 0x33, 0xe7, 0xe3, 0x23, 0xec, 0x41, 0xf7, 0x6e, 0x7e, 0x9b, 0xce, 0xc6,
	0x6c, 0xe9, 0x9a, 0x1f, 0xbe, 0xfe, 0x0d, 0x00, 0x00, 0xff, 0xff, 0xff, 0xc0, 0x67, 0x6e, 0xfa,
	0x01, 0x00, 0x00,
}
